[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "zigcc-aarch64-musl"
cc = "zigcc-aarch64-musl"

[target.armv7-unknown-linux-musleabihf]
linker = "zigcc-armv7-musl"
cc = "zigcc-armv7-musl"