#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

EXTRA_COMMANDS="status"
EXTRA_HELP="        status          Check service status"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/tollgate-wrt
    procd_set_param directory /
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /tmp/tollgate-debug.log
    procd_set_param env TOLLGATE_DEBUG=1
    procd_set_param depends nodogsplash
    procd_set_param respawn 3600 5 0
    procd_close_instance
}

status() {
    if pgrep -f tollgate-wrt > /dev/null; then
        echo "tollgate-wrt is running (PID $(pgrep -f tollgate-wrt))"
    else
        echo "tollgate-wrt is stopped"
    fi
}
